package defpackage;

/* compiled from: r8-map-id-a8fcd33ccb3955d164982b21dfd7d15e244571037dfaf274f0981e5de3b0a2e0 */
/* loaded from: classes.dex */
public abstract class t31 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final zv D;
    public static final ww E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final zv I;
    public static final ww J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final zv N;
    public static final ww O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final zv S;
    public static final ww T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final zv X;
    public static final ww Y;
    public static final long Z;
    public static final ww a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final zv c0;
    public static final long d;
    public static final ww d0;
    public static final zv e;
    public static final long e0;
    public static final ww f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final zv h0;
    public static final long i;
    public static final ww i0;
    public static final zv j;
    public static final long j0;
    public static final ww k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final zv m0;
    public static final long n;
    public static final ww n0;
    public static final zv o;
    public static final long o0;
    public static final ww p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final zv r0;
    public static final long s;
    public static final ww s0;
    public static final zv t;
    public static final long t0;
    public static final ww u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final zv w0;
    public static final long x;
    public static final zv y;
    public static final ww z;

    static {
        zv zvVar = a41.a;
        ww wwVar = vy0.b;
        a = wwVar;
        b = jp0.i(24.0d);
        c = jp0.j(16);
        d = jp0.i(0.5d);
        zv zvVar2 = a41.b;
        e = zvVar2;
        f = wwVar;
        g = jp0.i(20.0d);
        h = jp0.j(14);
        i = jp0.i(0.2d);
        j = zvVar2;
        k = wwVar;
        l = jp0.i(16.0d);
        m = jp0.j(12);
        n = jp0.i(0.4d);
        o = zvVar2;
        p = wwVar;
        q = jp0.i(64.0d);
        r = jp0.j(57);
        long jI = jp0.i(0.2d);
        g21[] g21VarArr = f21.b;
        long j2 = jI & 1095216660480L;
        if (j2 == 0) {
            rz.a("Cannot perform operation for Unspecified type.");
        }
        s = jp0.l(j2, -f21.c(jI));
        t = zvVar2;
        u = wwVar;
        v = jp0.i(52.0d);
        w = jp0.j(45);
        x = jp0.i(0.0d);
        y = zvVar2;
        z = wwVar;
        A = jp0.i(44.0d);
        B = jp0.j(36);
        C = jp0.i(0.0d);
        D = zvVar2;
        E = wwVar;
        F = jp0.i(40.0d);
        G = jp0.j(32);
        H = jp0.i(0.0d);
        I = zvVar2;
        J = wwVar;
        K = jp0.i(36.0d);
        L = jp0.j(28);
        M = jp0.i(0.0d);
        N = zvVar2;
        O = wwVar;
        P = jp0.i(32.0d);
        Q = jp0.j(24);
        R = jp0.i(0.0d);
        S = zvVar2;
        T = wwVar;
        U = jp0.i(20.0d);
        V = jp0.j(14);
        W = jp0.i(0.1d);
        zv zvVar3 = a41.a;
        X = zvVar3;
        Y = wwVar;
        Z = jp0.i(16.0d);
        a0 = jp0.j(12);
        b0 = jp0.i(0.5d);
        c0 = zvVar3;
        d0 = wwVar;
        e0 = jp0.i(16.0d);
        f0 = jp0.j(11);
        g0 = jp0.i(0.5d);
        h0 = zvVar3;
        i0 = wwVar;
        j0 = jp0.i(28.0d);
        k0 = jp0.j(22);
        l0 = jp0.i(0.0d);
        m0 = zvVar2;
        n0 = wwVar;
        o0 = jp0.i(24.0d);
        p0 = jp0.j(16);
        q0 = jp0.i(0.2d);
        r0 = zvVar3;
        s0 = wwVar;
        t0 = jp0.i(20.0d);
        u0 = jp0.j(14);
        v0 = jp0.i(0.1d);
        w0 = zvVar3;
    }
}
